### ISSUE TITLE
Create home page view

### ISSUE THREAD

**Issue by seaniemc** [sarbjeetkumar/GoProject#19]
Create a html file that is load into the index.html view when the website is loaded.

**Comment by jasonthorne** [comment]
Welcome modal set up.

**Comment by seaniemc** [comment]
Hey Jason. Can you tell me how the model works on the website. Do we need to do anything special to get it to run? Thanks

**Comment by jasonthorne** [comment]
Hi Sean. The modal box should automatically pop up the first time you navigate to the page. After that it wont show though, due to a cookie preventing it from doing so. To show it again you can either delete the cookie, or click the 'show message again' text that I added to the bottom left of the page. 

Any problems seeing it, let me know.
