### ISSUE TITLE
File structure not appearing locally. bin and src hideen

### ISSUE THREAD

**Issue by seaniemc** [sarbjeetkumar/GoProject#7]

**Comment by seanJosephFitzpatrick** [comment]
Added text files test.txt to empty folders.

Git cannot track empty directories by design (an empty directory has no content, while git tries to track content). You can add a placeholder file (an empty file ought to be enough) if you want to add the directory, or live with the limitation. 
http://stackoverflow.com/questions/8281322/uploading-a-empty-folder-to-github
